@startuml

title **Assign New User Role Group Sequence**

box
participant controller
participant model
database databases
end box

activate controller
controller -> model ++ : RoleGroupModel->asignTo(user)
model -> model : UserRoleGroupsModel->insert()
model -> databases ++ : insert UserRoleGroup
return
model --> controller
@enduml