@startuml

title **Remove Assigned User Role Group Sequence**

box
participant controller
participant model
database databases
end box

activate controller
controller -> model ++ : RoleGroupModel->removeAsignedRoleTo(user)
model -> model  : UserRoleGroupsModel->delete()
model -> databases ++ : delete UserRoleGroup
return
model --> controller
@enduml