@startuml

' frogot password
actor  user
participant webapp
participant view
participant controller
participant model
database databases

user -> webapp : get forgot password
webapp -> controller : get UserController->resetPassword()
controller --> view : reset password page
view --> user
user -> webapp : post forgot passord
webapp -> controller : post UserController->resetPassword(email)
controller -> model : UserModel->findByEmail(email)
model -> databases : read User
databases --> model
model --> controller
controller -> model : ResetPasswordModel->insert(user)
model -> databases : save ResetPasswordKeys
databases --> model
model -> model : send reset link
model --> controller
controller --> view : success page
view --> user

@enduml