@startuml

' logout
actor  userAuthenticated
participant webapp
participant view
participant controller
participant model
database databases

userAuthenticated -> webapp : get logout
webapp -> controller : UserController->logout()
controller -> model : UserModel->doLogout()
model -> databases : delete Session
databases --> model
model --> controller
controller -> model : SessionModel->insert()
model -> databases : insert Session
databases --> model
model --> controller
controller --> view : login page
view --> userAuthenticated



@enduml