@startuml

' reset password
actor  user
participant webapp
participant view
participant controller
participant model
database databases

user -> webapp : get reset password with key
webapp -> controller : get UserController->reset(key)
controller -> model : ResetPasswordKeys->find(key)
model -> databases : read ResetPasswordKeys
databases --> model
model --> controller
controller --> view : reset password page
view --> user
user -> webapp : post new cred
webapp -> controller : post UserController->reset(password)
controller -> model : UserModel->changePassword(password)
model -> databases : update Users
databases --> model
model --> controller
controller --> view : success page
view --> user


@enduml