@startuml

' reset password
actor  userAdmin
participant webapp
participant view
participant controller
participant model
database databases

userAdmin -> webapp : get user list
webapp -> controller : get UserController->list()
controller -> model : UserModel->findAll()
model -> databases : read Users
databases --> model
model --> controller
controller --> view : user list page
view --> userAdmin

@enduml